name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    
    - name: Create src directory if it doesn't exist
      run: |
        mkdir -p src
        touch src/index.js
        echo "import React from 'react';" > src/index.js
        echo "import ReactDOM from 'react-dom';" >> src/index.js
        echo "import App from './App';" >> src/index.js
        echo "ReactDOM.render(<App />, document.getElementById('root'));" >> src/index.js
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Test
      run: npm test -- --passWithNoTests
    
    - name: Deploy to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy to S3
      run: aws s3 sync build/ s3://ragops-frontend --delete
    
    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id E1J1UKJPMJ1IY0 --paths "/*"